chore: add dependabot, codespell (#12)

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -6,6 +6,12 @@ if (git diff --cached --name-only | grep --silent '\.go$'); then
     make generate
     git add *_string.go
 
+    make spell
+    if [ $? -ne 0 ]; then
+        echo "codespell found issues. Please fix them before committing. Commit aborted."
+        exit 1
+    fi
+
     make lint
     if [ $? -ne 0 ]; then
         echo "golangci-lint failed. You can try 'make fix' to automatically fix some issues. Commit aborted."
